name: Demo to Delpoy OAS to Kong # Specify the name of the deployment
on:
  push:
    branches:
      - master  # Trigger the deployment when pushing to the main branch
#g
jobs:
  OAS_To_KONG:
    runs-on: ubuntu-latest  # Use Ubuntu as the operating system for the job
           
    steps:
    - name: Checkout Code  # Checkout the code from the repository
      uses: actions/checkout@v2
  
    - name: Setup Python and dependencies
      uses: actions/setup-python@v2
      with:
          python-version: '3.x' # Version range or exact version of a Python version to use, using SemVer's version range syntax
          architecture: 'x64' # optional x64 or x86. Defaults to x64 if not specified
    - run: |
         pip install pyrebase4==4.6.0
         pip install requests==2.26.0
         pip install requests_toolbelt==0.9.1
   
    - name: Install Insomnia CLI  # Install Insomnia CLI for linting and generating Kong configuration
      run: |
        wget https://github.com/Kong/insomnia/releases/download/lib%403.14.0-beta.1/inso-linux-3.14.0-beta.1.tar.xz
        tar -xf inso-linux-3.14.0-beta.1.tar.xz
#       install python for running the script
 

          # write the Credential json secrect key from git_secrect
    - name: get secrect key
      id: write_key_file
      uses: timheuer/base64-to-file@v1
      with:
        fileName: 'key.json' # name of the written key file
        encodedString: ${{ secrets.GCS_SA_KEY }} # Secret stored in Github secrets    
            # run the upload script

    
    - name: Installing NodeJs
      uses: actions/setup-node@v1
      
    - name: Installing inso
      run:  npm install -g insomnia
      
    - name: Lint OpenAPI Spec
      run: ./inso lint spec pipe1.yml
      
    - name: Generate Kong configuration in declarative format
      run: ./inso generate config pipe1.yml --type declarative -o kong.yaml --kongVersion 3
 
    - name: install deck CLI  # Install deck CLI for syncing Kong configuration
      run: |
        curl -sL https://github.com/kong/deck/releases/download/v1.17.2/deck_1.17.2_linux_amd64.tar.gz -o deck.tar.gz
        tar -xf deck.tar.gz -C /tmp 
        sudo cp /tmp/deck /usr/local/bin/

    - name: Validate the Kong configuration using deck CLI
      run:  deck dump -o dump.yaml --kong-addr http://34.125.43.26:8001
    - name: run upload script
      run: python /home/runner/work/KongApiops/KongApiops/upload.py
        
      
    - name: Validate the Kong configuration using deck CLI
      run:  deck validate -s kong.yaml
      

    - name: Deploy to Kong
      run: deck sync -s kong.yaml --kong-addr http://34.125.43.26:8001
